# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr1d=np.arange(10)
arr2d=arr1d.reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [14]:
ones=np.full((2,5),1)
vstack=np.vstack((arr2d,ones))
vstack

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [16]:
hstack=np.hstack((arr2d,ones))
hstack

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [18]:
arr2d.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [21]:
array3d=np.arange(15).reshape(3,5)
array3d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [22]:
vector=np.arange(15)
matrix=vector.reshape(5,3)
matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [29]:
array=np.arange(25).reshape(5,5)
square=np.power(array,2)
square


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [34]:
arr=np.random.randint(0,99999,size=(5,6))
meanarr=np.mean(arr)
meanarr


55375.666666666664

## Question:9

### Find the standard deviation of the previous array in Q8?

In [37]:
deviation=np.std(arr)
deviation

30504.581183087164

## Question:10

### Find the median of the previous array in Q8?

In [38]:
median=np.median(arr)
median

63009.0

## Question:11

### Find the transpose of the previous array in Q8?

In [40]:
transpose=np.transpose(arr)
transpose

array([[72493, 20245, 89940, 70165, 92932],
       [14039, 13538, 71544, 91114, 35486],
       [95134, 27666, 20415, 73379, 52157],
       [53404, 96035, 66456, 14537,  2597],
       [86376, 40006, 17767, 53133, 59562],
       [72956, 96988, 70349, 83743,  7114]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [45]:
array1=np.arange(16).reshape(4,4)
diagsum=np.trace(array1)
diagsum

30

## Question:13

### Find the determinant of the previous array in Q12?

In [56]:
det=np.linalg.det(array1)
det

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [64]:
percentile=np.percentile(array1,(5,90))
percentile

array([ 0.75, 13.5 ])

## Question:15

### How to find if a given array has any null values?

In [65]:
nan=np.isnan(array1)
nan

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])