# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [169]:
import numpy as np

2. Create a null vector of size 10 

In [170]:
null=np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [171]:
a=np.array(np.arange(10,50))
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [172]:
a.shape

(40,)

5. Print the type of the previous array in question 3

In [173]:
a.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [174]:
np.version.version

'1.18.1'

7. Print the dimension of the array in question 3


In [175]:
a.ndim

1

8. Create a boolean array with all the True values

In [176]:
array=np.full((2,2),True)
array


array([[ True,  True],
       [ True,  True]])

9. Create a two dimensional array




In [177]:
array2=np.arange(20).reshape(4,5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

10. Create a three dimensional array



In [212]:
array3=np.arange(30).reshape(3,2,5)
array3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [213]:
array3[::-1,::-1,::-1]

array([[[29, 28, 27, 26, 25],
        [24, 23, 22, 21, 20]],

       [[19, 18, 17, 16, 15],
        [14, 13, 12, 11, 10]],

       [[ 9,  8,  7,  6,  5],
        [ 4,  3,  2,  1,  0]]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [180]:
null1=np.zeros(10)
null1[4]=1
null1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [181]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [182]:
arr = np.array([1, 2, 3, 4, 5],dtype=np.float64)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [183]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
mul=arr1*arr2
mul

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [184]:
arr1+arr2

array([[ 1.,  6.,  4.],
       [11.,  7., 18.]])

17. Extract all odd numbers from arr with values(0-9)

In [185]:
arr[arr%2==1]

array([1., 3., 5.])

18. Replace all odd numbers to -1 from previous array

In [186]:
arr[0]=-1
arr[2]=-1
arr[4]=-1
arr

array([-1.,  2., -1.,  4., -1.])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [187]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [188]:
arr2d=np.arange(30).reshape(5,6)
arr2d[0]=1
arr2d[::,0:1]=1
arr2d[::,-1]=1
arr2d[4]=1
arr2d[1:4,1:5]=0
arr2d

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [189]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [190]:
arr2d[::]=64
arr2d

array([[64, 64, 64],
       [64, 64, 64],
       [64, 64, 64]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [191]:
array2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
array2d[0]



array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [192]:
array2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
array2d[1,1]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [193]:
array2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
array2d[::,3:4]


array([[3],
       [8]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [194]:
random=np.random.randn(10,10)
print(np.max(random))
print(np.min(random))

2.3954537805379768
-2.3858043234666524


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [195]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [196]:
np.where(np.in1d(a,b))

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [197]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!='Will']

array([[-1.51671577,  0.34436037, -1.06349562, -0.80528218],
       [-0.38768722,  1.06039084, -0.73246626,  0.05779268],
       [-1.09088051, -0.66775231,  2.03523233, -1.86333106],
       [-0.50585106,  0.89329622, -0.28846371, -0.25350935],
       [ 0.31216425,  0.41438647,  0.49932407, -0.0951737 ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [198]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[((names!='Will') & (names!='Joe'))]



array([[ 0.97553125, -0.22825219, -1.63591589, -0.98199404],
       [ 0.22051955, -0.81671216,  1.47850675, -0.42363747]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [199]:
arr2d=np.arange(1,16,dtype=np.float32).reshape(5,3)
arr2d


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]], dtype=float32)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [200]:
arr=np.arange(1,17,dtype=np.float32).reshape(2,2,4)
arr

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float32)

33. Swap axes of the array you created in Question 32

In [201]:
arr.T

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]], dtype=float32)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [202]:
array=np.linspace(0,2,10)
sqrt=np.sqrt(array)
print(sqrt)
np.where(sqrt<0.5,0,sqrt)


[0.         0.47140452 0.66666667 0.81649658 0.94280904 1.05409255
 1.15470054 1.24721913 1.33333333 1.41421356]


array([0.        , 0.        , 0.66666667, 0.81649658, 0.94280904,
       1.05409255, 1.15470054, 1.24721913, 1.33333333, 1.41421356])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [203]:
arr1=np.random.randn(12)
arr2=np.random.randn(12)
maxarr=np.maximum(arr1,arr2)
maxarr

array([ 1.35063973,  0.40203084,  0.52057787, -0.05512436,  0.29625363,
        0.14873997,  0.04039562,  0.36523692,  1.31509151, -0.52385328,
        0.76408407,  0.93081375])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [204]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique=np.unique(names)
unique.sort()
unique

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [205]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
intersect=np.intersect1d(a,b)
print(np.where(a==intersect))
a=np.delete(a,[4])
a


(array([4], dtype=int64),)


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [206]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[::,2]=newColumn
sampleArray


array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [207]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot=np.dot(x,y)
dot

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [208]:
matrix=np.random.randint(0,100,size=20).reshape(2,10)
print(matrix)
cumsum=np.cumsum(matrix)
cumsum

[[77 10 29 68 20  5 69  8 63 81]
 [29 24 91 37 20 47 39 63 54  2]]


array([ 77,  87, 116, 184, 204, 209, 278, 286, 349, 430, 459, 483, 574,
       611, 631, 678, 717, 780, 834, 836], dtype=int32)